name: Trigger auto deployment for acatests

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/acatests-AutoDeployTrigger-f4e56d1b-c997-45b3-9f6e-b6ddf880ddb8.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ACATESTS_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ACATESTS_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ACATESTS_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.ACATESTS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ACATESTS_REGISTRY_PASSWORD }}
          containerAppName: acatests
          resourceGroup: azuretestlogs
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


